schema:
  - https://graphql.datocms.com:
      headers:
        Authorization: "Bearer $DATO_TOKEN"
documents: './src/graphql/**/*.graphql'
generates:
  src/graphql/generated.ts:
    plugins:
      - typescript
      - typescript-operations
      - typed-document-node
    config:
      strictScalars: true
      scalars:
        BooleanType: boolean
        CustomData: Record<string, unknown>
        Date: string
        DateTime: string
        FloatType: number
        IntType: number
        ItemId: string
        JsonField: unknown
        MetaTagAttributes: Record<string, string>
        UploadId: string
      # Optional, gives meta fields a leading underscore
      namingConvention:
        # enumValues: './pascalCaseWithUnderscores'
