import React from "react";
import { Button } from "./button";
import figma from "@figma/code-connect";

/**
 * -- This file was auto-generated by `figma connect create` --
 * `props` includes a mapping from Figma properties and variants to
 * suggested values. You should update this to match the props of your
 * code component, and update the `example` function to return the
 * code example you'd like to see in Figma
 */

figma.connect(
  Button,
  "https://www.figma.com/design/mxkG7HImbb10ok2UofokjW/ESPI-Website-2024---Dev-Handover?node-id=2004-2770&t=ARuCITCRQvFR7TCS-4",
  {
    props: {
      color: figma.enum("Color", {
        Black: "black",
        White: "white",
      }),
      icon: figma.enum("Icon", {
        Plus: "plus",
        Arrow: "arrow",
        "Arrow Down": "arrow-down",
        "New Tab": "new-tab",
        Download: "download",
      }),
      test: figma.string("Test"),
    },
    example: (props) => <Button text="View our work" />,
  },
);
